apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "neo4j-db.fullname" . }}
  labels:
    {{- include "neo4j-db.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "neo4j-db.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "neo4j-db.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: bolt
              containerPort: 7687
              protocol: TCP
            - name: http
              containerPort: 7474
              protocol: TCP
          env:
            - name: NEO4J_AUTH
              value: "{{ .Values.neo4j.auth.username }}/{{ .Values.neo4j.auth.password }}"
            - name: NEO4J_server_config_strict__validation_enabled
              value: "false"
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: data
              mountPath: /data
            {{- end }}
          readinessProbe:
            tcpSocket:
              port: 7687
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 7687
            initialDelaySeconds: 60
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        {{- if .Values.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "neo4j-db.fullname" . }}-pvc
        {{- end }}
