apiVersion: v1
kind: Service
metadata:
  name: {{ include "neo4j-db.fullname" . }}
  labels:
    {{- include "neo4j-db.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.boltPort }}
      targetPort: 7687
      protocol: TCP
      name: bolt
    - port: {{ .Values.service.httpPort }}
      targetPort: 7474
      protocol: TCP
      name: http
  selector:
    app: {{ include "neo4j-db.name" . }}
    release: {{ .Release.Name }}
