env:
  NODE_ENV: "development"
  PORT: "4025"
  NEO4J_URI: "bolt://neo4j-db.recommender.svc.cluster.local:7687"
  NEO4J_USER: "neo4j"
  NEO4J_PASSWORD: "password"

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 512Mi
